import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { createClient } from "@/lib/supabase/server";

const InterFont = Inter({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" className={`${InterFont.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar CURRENT_USER={user}>{children}</Navbar>
      </body>
    </html>
  );
}
