import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const InterFont = Inter({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${InterFont.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar>{children}</Navbar>
      </body>
    </html>
  );
}
